console.log('test PR template')
console.log('첫번째 커밋')
console.log('두번째 커밋')
console.log('김치볶음밥 만들기')
console.log('식용유 두르기')
console.log('김치 넣기')
console.log('양파 썰기')
console.log('고기 썰기')
console.log('피망 썰기')
console.log('5분간 볶습니다')
console.log('간장 넣기')
console.log('설탕 넣기')
console.log('새우 넣기')
console.log('완성!')
console.log('1')
console.log('2')
console.log('3')
console.log('맛있다!')

console.log('2번째 김치 볶음밥')
