console.log('test PR template')
console.log('첫번째 커밋')
console.log('두번째 커밋')
console.log('김치볶음밥 만들기')
console.log('식용유 두르기')
console.log('김치 넣기')
console.log('양파 썰기')
console.log('고기 썰기')
console.log('5분간 볶습니다')